### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [KyleCRat/TC359_Project_Four#1]
:+1: Very nice! Something I do notice though is that there's a lot of "cruft" in this project (i.e. files we don't ever use). That makes it less pleasant to browse through and is generally seen as unprofessional. Can you delete the extra files in this and future projects?

These include:

- the `TempHTMLCSS` folder and its contents in the project root
- the `css` folder and its contents in the project root
- the `style.css` file in the project root
- the numbered `index1/2/3.html` files in the views folder
- and more

If you've already deleted these locally and are confused as to why they're still showing up in your repo, even after a `git add .` and commit, then you may just need to make a commit after `git add -A .` instead. The extra `-A` parameter tells git to track not only new and modified files, but also deleted files.

**Comment by KyleCRat** [comment]
Cleaned the directory. Shouldn't be any temporary files any longer.
